### ISSUE TITLE
Unable to add the repository with Home Assistant 2022.11.5

### ISSUE THREAD

**Issue by SylvainGa** [jgoakley/hassio-addons#5]
Hi, the addon was working great under 2021.8.6 but needed to upgrade and now, all my entities are showing as 'unavailable'. Tried to see if there was an updated one but when I add https://github.com/jgoakley/hassio-addons as addon, it doesn't show up. The following shows up in the supervisor log file if it can be of any help:

```
22-12-06 23:02:09 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/jgoakley/hassio-addons repository
22-12-06 23:02:10 WARNING (SyncWorker_0) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of LIRC
22-12-06 23:02:10 WARNING (SyncWorker_0) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of LIRC
22-12-06 23:02:10 INFO (MainThread) [supervisor.store] Loading add-ons from store: 74 all - 3 new - 0 remove
```

Have you tried your addon with that version of HA?

Thanks.

**Comment by comatose1978** [comment]
I am having this issue as well.
I love the integration, could you look into it when you get a chance? 

Thanks

![1861F81E-1F4E-47AA-9C99-E6918E57D8D6](https://user-images.githubusercontent.com/68303452/206917579-67ac8610-6efd-47a7-8a23-29ac8a6ec2a1.jpeg)

**Comment by SylvainGa** [comment]
In my case. I went with pushing my WeeWx data through MQTT and reading them from there as such:

```
mqtt:
  sensor:
    - name: "acurite_outside_temperature"
      state_topic: "acurite/loop"
      unit_of_measurement: '°C'
      value_template: "{{ value_json.outTemp_C | round(1, default=none) }}"
      unique_id: "acurite_outtemp"

```
